### ISSUE TITLE
npm install报错，sass包404，并且最后编译直接报错

### ISSUE THREAD

**Issue by Fury76** [jack15083/laravel-admin#7]
执行npm install报错，提示node-sass的git地址404。最终编译直接报错！

vagrant@homestead:~/Project/laravel-admin-eu$ npm install

> node-sass@4.9.4 install /home/vagrant/Project/laravel-admin-eu/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-72_binding.node":

HTTP error 404 Not Found

省略一万字。。。。

In file included from ../src/binding.cpp:1:0:
../../nan/nan.h: In instantiation of ‘void Nan::imp::SetMethodAux(T, v8::Local<v8::String>, v8::Local<v8::FunctionTemplate>, ...) [with T = v8::Local<v8::Object>]’:
../../nan/nan.h:2394:20:   required from ‘void Nan::SetMethod(HandleType<T>, const char*, Nan::FunctionCallback) [with T = v8::Object; HandleType = v8::Local; Nan::FunctionCallback = void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)]’
../src/binding.cpp:351:42:   required from here
../../nan/nan.h:2378:3: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   recv->Set(name, GetFunction(tpl).ToLocalChecked());
   ^~~~
In file included from /home/vagrant/.node-gyp/12.5.0/include/node/v8-internal.h:14:0,
                 from /home/vagrant/.node-gyp/12.5.0/include/node/v8.h:25,
                 from /home/vagrant/.node-gyp/12.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:52,
                 from ../src/binding.cpp:1:
/home/vagrant/.node-gyp/12.5.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/vagrant/.node-gyp/12.5.0/include/node/v8config.h:326:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
binding.target.mk:127: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/vagrant/Project/laravel-admin-eu/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/Project/laravel-admin-eu/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-54-generic
gyp ERR! command "/usr/bin/node" "/home/vagrant/Project/laravel-admin-eu/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/vagrant/Project/laravel-admin-eu/node_modules/node-sass
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-09-04T03_14_50_159Z-debug.log

**Comment by jack15083** [comment]
使用 cnpm install node-sass， 单独安装试下看。
